    print(opponent)
    print("-----")
    print("OPPONENT")
    print("")
    print(discard.peek())
    print("")
    print("YOU")
    print("-----")
    print(you)

    user_action = input()

    print("GAME STARTED!")
    time.sleep(0.5)
    print("3...", end="", flush=True)
    time.sleep(0.5)
    print("2...", end="", flush=True)
    time.sleep(0.5)
    print("1...", end="", flush=True)
    time.sleep(0.5)
    print("CAMBIO!", flush=True)
    time.sleep(0.5)
    os.system('clear')


    print(opponent)
    print("-----")
    print("OPPONENT")
    print("")
    print(discard.peek())
    print("")
    print("YOU")
    print("-----")
    print(you)